services:
  projeto_02:
    env_file:
      - path: ./devcontainer.env
        required: false
    build: 
      context: .
      dockerfile: Dockerfile
    image: kaggle_light
    volumes:
      - ./projeto_02:/kaggle
    ports:
      - 8888:8888
    command: "jupyter notebook --notebook-dir=/kaggle/working --ip=0.0.0.0 --port=8888 --no-browser --allow-root --ServerApp.token='' --ServerApp.password=''"
  